apiVersion: v2
name: flux2-sync
type: application
version: 1.16.0
appVersion: 2.9.1
description: A Helm chart for flux2 GitRepository to sync with
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Feat]: add field kustomization.spec.ignore"
