{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: helm-controller
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: source-controller
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: notification-controller
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: image-automation-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
