{{- if and .Values.imagereflectorcontroller.create }}
{{- if .Values.imagereflectorcontroller.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  {{- with .Values.imagereflectorcontroller.serviceaccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
