{{- if and .Values.kustomizecontroller.create }}
{{- if .Values.kustomizecontroller.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  {{- with .Values.kustomizecontroller.serviceaccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
