{{- if and .Values.kustomizecontroller.create }}
{{- if .Values.kustomizecontroller.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: flux
  name: kustomize-controller
  {{- with .Values.kustomizecontroller.serviceaccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
