{{- if and .Values.notificationcontroller.create }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller
  name: notification-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  type: ClusterIP
{{- end }}
