{{- if .Values.sourcecontroller.create -}}
{{- if .Values.sourcecontroller.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: flux
  name: source-controller
  {{- with .Values.sourcecontroller.serviceaccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
