{{- if .Values.sourcecontroller.create }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller
  name: source-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  type: ClusterIP
{{- end }}
