{{- if and (.Values.secret.create) (not .Values.secret.data) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-generate-git-secret"
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
        app.kubernetes.io/part-of: flux
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ .Release.Name }}-generate-git-secret"
      containers:
      - name: flux-cli
        image: {{ template "template.image" .Values.cli }}
        command: 
          ["/usr/local/bin/flux", "create",  "secret", "git", {{ .Release.Name }},
          "--url={{ .Values.gitRepository.spec.url }}",
          "--ssh-key-algorithm={{ .Values.secret.generate.sshKeyAlgorithm }}",
          "--ssh-ecdsa-curve={{ .Values.secret.generate.sshEcdsaCurve }}",
          "--namespace={{ .Release.Namespace }}",
          ]
      {{- with .Values.cli.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cli.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cli.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}