apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  url: {{ .Values.gitRepository.spec.url }}
  {{- with .Values.gitRepository.spec.secretRef }}
  secretRef: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.gitRepository.spec.interval }}
  interval: {{ .Values.gitRepository.spec.interval }}
  {{- end }}
  {{- if .Values.gitRepository.spec.timeout }}
  timeout: {{ .Values.gitRepository.spec.timeout }}
  {{- end }}
  {{- with .Values.gitRepository.spec.ref }}
  ref: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gitRepository.spec.verify }}
  verify: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.gitRepository.spec.ignore }}
  ignore: {{ .Values.gitRepository.spec.ignore }}
  {{- end }}
  {{- if .Values.gitRepository.spec.suspend }}
  suspend: {{ .Values.gitRepository.spec.suspend }}
  {{- end }}
  {{- if .Values.gitRepository.spec.gitImplementation }}
  gitImplementation: {{ .Values.gitRepository.spec.gitImplementation }}
  {{- end }}
  {{- if .Values.gitRepository.spec.recurseSubmodules }}
  recurseSubmodules: {{ .Values.gitRepository.spec.recurseSubmodules }}
  {{- end }}
  {{- with .Values.gitRepository.spec.include }}
  include: {{ toYaml . | nindent 4 }}
  {{- end }}
