{{- if .Values.secretlist}}
{{- range $key, $secret := .Values.secretlist }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
  name: {{ $secret.name }}
  namespace:  {{ $.Release.Namespace }}
type: Opaque
{{ tpl (toYaml $secret.value ) $ }}
{{- end }}
{{- end }}
